# Generated by Django 4.2.7 on 2024-03-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Celulares', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('marca', models.CharField(blank=True, choices=[('Playstation 5', 'Playstation 5'), ('Playstation 4', 'Playstation 4'), ('Xbox Series X/S', 'Xbox Series X/S'), ('Xbox One', 'Xbox One'), ('Nintendo Switch', 'Nintendo Switch'), ('PC', 'PC')], max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='webVentas')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
