# Generated by Django 4.2.7 on 2024-04-01 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Celulares', '0002_celular_delete_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celular',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='celular',
            old_name='photo',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='celular',
            old_name='price',
            new_name='precio',
        ),
    ]
